### ISSUE TITLE
Won't let me stop a density program half way through and resume later

### ISSUE THREAD

**Issue by hollyallen8** [bdavis222/dotscanner#12]
Did a few images with the density program. Closed it. Went back to it and got an error

<img width="272" alt="image" src="https://user-images.githubusercontent.com/108499643/232254872-e2ac8f4e-7a25-41bb-bc61-240d7762afc5.png">

**Comment by hollyallen8** [comment]
<img width="1366" alt="Screenshot 2023-04-15 at 3 57 57 PM" src="https://user-images.githubusercontent.com/108499643/232254896-68fffef1-ca5a-477e-93cf-6afbfac99f2e.png">

**Comment by bdavis222** [comment]
Unable to repro the issue, but may have found the culprit. Marking this as fixed, but feel free to reopen if the problem persists.
